# Generated by Django 4.1.7 on 2023-06-19 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimarket', '0002_producto_cantidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
